name: tests-and-linters

on:
  - pull_request
  - push

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        go-version:
          - 1.15
          - 1.16
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...

  super-linter:
    name: Run Super-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Super-Linter
        uses: github/super-linter@v3.17.0
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GO: false # Go linting is broken for now, see: https://github.com/github/super-linter/issues/143
          VALIDATE_JSCPD: false # TODO(dfurman): consider configuring this linter

  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43

  check-go-mod:
    name: Check Go module consistency
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        id: go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check Go module consistency
        run: ./tools/check_go_mod.sh
